name: EnvyFactionCorePM
author: Tethered_, anullihate
description: Factions Plugin for EnvyGames Faction Server
version: 1.3.20
main: anullihate\EnvyFactionCorePM\FactionMain
api: [3.0.0]
depend:
  - "PurePerms"
softdepend: ["AntiSpamPro"]
extensions: [sqlite3]
commands:
  f:
    description: use /f help for all parameters
    permission: f.command
  shop:
    description: "open shop ui"
    permission: shop.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
  shop.command:
    default: true
    description: 'allows you to use shop command'
